[package]
name = "cdo"
description = "Runs a command in the given directory"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.69"
clap = { version = "4.1.6", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.8"
tempfile = "3.3.0"
