[package]
name = "cdo"
description = "Runs a command in the given directory"
version = "0.1.0"
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
clap = { version = "4.4.4", features = ["derive"] }

[dev-dependencies]
assert_cmd = "2.0.12"
tempfile = "3.8.0"
