name: Nix CI

on:
  pull_request: {}
  push:
    branches:
      - main

jobs:
  nix-flake-check:
    name: nix flake check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          # Helps avoid rate limiting
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake check --all-systems --keep-going

  nix-build:
    name: nix build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          # Helps avoid rate limiting
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build

  nix-format-check:
    name: check .nix files format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v23
        with:
          # Helps avoid rate limiting
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: find . -iname '*.nix' -print0 | xargs -0 -t nix develop -c nixpkgs-fmt --check
